package rw.health.ubuzima.enums;

public enum EventType {
    HEALTH_EDUCATION,
    WORKSHOP,
    SEMINAR,
    SUPPORT_GROUP_MEETING,
    HEALTH_SCREENING,
    VACCINATION_CAMPAIGN,
    COMMUNITY_OUTREACH,
    AWARENESS_CAMPAIGN,
    TRAINING_SESSION,
    CONFERENCE,
    WEBINAR,
    CONSULTATION,
    OTHER
}
